name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label: 'feature'
  - title: 'ğŸ› Fixes'
    label: 'bug'
  - title: 'ğŸ”¥ Hotfixes'
    label: 'hotfix'
  - title: 'ğŸ¿ ETC'
    label: 'etc'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Uncategorised (Please update its labelğŸ™ğŸ»)

  # What's Changed
  $CHANGES